### PR TITLE
Update raiden and raiden-contracts

### PR DESCRIPTION
**Pull request by pirapira**
This brings in `raiden:develop` again, and upgrades `raiden-contracts`.

### CODE REVIEW

**Comment by pirapira** [comment]
I don't understand what failed in the CI https://circleci.com/gh/raiden-network/raiden-services/287?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Is this because of `raiden` upgrade or `raiden-contracts` upgrade?

**Comment by palango** [comment]
It's because of the raiden update. I'll start working on this now, I'll let you know once that update is finished.

**Comment by palango** [comment]
@pirapira I'll incorporate this into #574

**Comment by pirapira** [comment]
Thank you!

**Pull request closed without merging**
